spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wink-dns
  mvc:
    log-resolved-exception: false

app:
  jwt:
    key: (secret-key)
    expiration-hours: 168
  wink:
    client-id: (client-id)
    client-secret: (client-secret)
  aws:
    access-key: (access-key)
    secret-key: (secret-key)
    region: ap-northeast-2
    route53:
      hosted-zone-id: (hosted-zone-id)

server:
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force-response: true
